language: php

php:
    - '5.6'
    - '7.1'
    - '7.2'

matrix:
  include:
    - php: '5.3'
      dist: precise
    - php: '5.4'
      dist: trusty
    - php: '5.5'
      dist: trusty
    - php: '7.0'
      dist: trusty

before_install:
  - phpenv config-add tests/travis/php$TRAVIS_PHP_VERSION.ini

install:
  - export TRAVIS_PHP_VERSION; sh tests/travis/install-script.sh

script: 
  - sh tests/travis/run-test.sh
